on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: 🔨 Build Project
        run: |
          npm install

      - name: Restart Node.js App on cPanel
        run: |
          curl -X POST \
          --user ${{ secrets.C_USER }}:${{ secrets.C_PASSWORD }} \
          https://test.adawat360.com:2083/json-api/cpanel \
          -d "cpanel_jsonapi_user=${{ secrets.C_USER }}" \
          -d "cpanel_jsonapi_apiversion=2" \
          -d "cpanel_jsonapi_module=Nodejs" \
          -d "cpanel_jsonapi_func=start" \
          -d "app_directory=/home/adawazuo/test.adawat360.com/"

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD}}
